# Generated by Django 3.1.5 on 2021-03-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio_file',
        ),
    ]
