# Generated by Django 3.1.5 on 2021-04-07 02:34

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_sharedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choose_file',
            field=models.FileField(blank=True, null=True, upload_to='static/media/mediaFiles', validators=[news.validators.validate_file_extension]),
        ),
    ]
