# Generated by Django 3.1.5 on 2021-02-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_profile_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('release_date', models.DateTimeField()),
                ('album_art', models.ImageField(upload_to='static/media/albumPictures')),
                ('genre', models.CharField(default='', max_length=20)),
                ('explicit', models.BooleanField(default=False)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
    ]
