# Generated by Django 3.1.5 on 2021-02-18 19:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20210218_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
        ),
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 14, 51, 36, 592907)),
        ),
    ]
