# Generated by Django 3.1.5 on 2021-03-24 17:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0010_auto_20210317_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 13, 37, 10, 154940)),
        ),
        migrations.CreateModel(
            name='NotificationBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationType', models.CharField(default='NONE', max_length=20)),
                ('following', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.following')),
                ('friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.friends')),
                ('friendRequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.friendrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifReceiver', to=settings.AUTH_USER_MODEL)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.notificationbridge')),
            ],
        ),
    ]
