# Generated by Django 3.1.5 on 2021-03-24 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20210324_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 13, 45, 45, 504129)),
        ),
        migrations.AlterField(
            model_name='notificationbridge',
            name='following',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.following'),
        ),
        migrations.AlterField(
            model_name='notificationbridge',
            name='friend',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.friends'),
        ),
        migrations.AlterField(
            model_name='notificationbridge',
            name='friendRequest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.friendrequest'),
        ),
    ]
