# Generated by Django 3.1.5 on 2021-03-25 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20210324_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 16, 45, 21, 374244)),
        ),
    ]
