# Generated by Django 3.1.5 on 2021-03-25 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20210325_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 17, 36, 57, 481365)),
        ),
    ]
