# Generated by Django 3.1.5 on 2021-03-26 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_auto_20210325_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 20, 58, 6, 518724)),
        ),
    ]
