# Generated by Django 3.1.5 on 2021-04-02 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_auto_20210325_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 20, 33, 11, 78829)),
        ),
    ]
