# Generated by Django 3.1.5 on 2021-04-02 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_sharedpost'),
        ('user_profile', '0016_auto_20210401_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationbridge',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.comment'),
        ),
        migrations.AddField(
            model_name='notificationbridge',
            name='share',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.sharedpost'),
        ),
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 16, 25, 13, 248947)),
        ),
    ]
