# Generated by Django 3.1.5 on 2021-04-15 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_auto_20210406_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 17, 18, 43, 757656)),
        ),
    ]
