from django.db import models
from django.contrib.auth.models import User, Group, Permission
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    User._meta.get_field('email')._unique = True
    first_name = models.CharField(max_length=20,default="")
    last_name = models.CharField(max_length=20,default="")
    bio = models.CharField(max_length=500,default="n/a")
    photo = models.ImageField(upload_to='static/media/profilePictures')
    following = models.IntegerField(default = 0)
    followers = models.IntegerField(default = 0)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Music(models.Model):
    #id is the primary key, generated by django itself
    name = models.CharField(default="", max_length =32)
    artist = models.ForeignKey(User, on_delete=models.CASCADE)
    release_date = models.DateTimeField(default =datetime.now())
    album_art = models.ImageField(upload_to='static/media/albumPictures')
    genre = models.CharField(default="", max_length = 20)
    explicit = models.BooleanField(default=False)

    def __str__(self):
        return self.name