# Generated by Django 3.1.5 on 2021-01-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20210119_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('ARTIST', 'ARTIST'), ('FAN', 'FAN')], default='FAN', max_length=6),
        ),
    ]
